### ISSUE TITLE
如何一单接口很多(几百个，比较混乱)，怎么有效管理？

### ISSUE THREAD

**Issue by numa001** [Hancoson/node-app#1]
`const myRoutes = (app) => {
  //home
  app.use('/', home);

  //pages
  app.get('/articles/:id', articles.getArticle);
  //edit
  app.get('/articles/:edit/:id', articles.editArticle);
  //add
  app.use('/add', function (req, res) {
    res.render('admin/add', {});
  });

  //admin
  app.use('/admin', admin);

  //接口
  app.get('/v1/:id', apis.getGroup);
  app.post('/v1/edit/:id', apis.postGroup);
  app.post('/v1/add', apis.addArticles);
  app.post('/v1/dele', apis.deleArticles);

  app.get('/aa', function (req, res) {
    res.send('aa')
  })

//如果下面还有很多的接口
app.get(添加分类)
app.get(修改分类)
app.get(xx分类)
.........
app.get(xx留言)
.......
}`

**Comment by Hancoson** [comment]
个人觉得有两个方面可以考虑：
- 代码层面
考虑使用restful的风格，类似：
```
app.get('/v1/edit/:id', apis.postGroup);
```
- 架构层面
把例如`edit`相关的独立出来，`edit.js`路由文件中
```
const edit = require('./edit');

app.use('/edit', edit);
```
